apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-ms
  labels:
    app: accounts-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-ms
  template:
    metadata:
      labels:
        app: accounts-ms
    spec:
      containers:
      - name: accounts-ms
        image: 03chandan/Accounts-MS:replaceImageTag
        ports:
        - containerPort: 8080
