apiVersion: v1
kind: Service
metadata:
  name: accounts-ms
  labels:
    app: accounts-ms
spec:
  type: NodePort
  selector:
    app: accounts-ms
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
